# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Harell < Formula
  desc "Command-line client for the Harell Data platform"
  homepage "https://harelldata.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/harelldata/homebrew-tap/releases/download/v0.1.0/harell_0.1.0_darwin_amd64.tar.gz"
      sha256 "2d4d66c3bb6cc598ab5054dff01ef49e5a0f13812e735b5d33b4c406e012f7c0"

      define_method(:install) do
        bin.install "harell"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/harelldata/homebrew-tap/releases/download/v0.1.0/harell_0.1.0_darwin_arm64.tar.gz"
      sha256 "77584cf2f9c6ec4636e8ff3ad37bf70e31fbbffbc1a94cf027af96e602e57475"

      define_method(:install) do
        bin.install "harell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/harelldata/homebrew-tap/releases/download/v0.1.0/harell_0.1.0_linux_amd64.tar.gz"
      sha256 "8ad09abebea989e24ef8ef935b2f958c74b6c61660c8e67774f01b5c51380253"
      define_method(:install) do
        bin.install "harell"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/harelldata/homebrew-tap/releases/download/v0.1.0/harell_0.1.0_linux_arm64.tar.gz"
      sha256 "8562a4a0b7c99e9f4205b0007ecc47b2f5776291fe0c51203384b39e98bc0f65"
      define_method(:install) do
        bin.install "harell"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/harell version")
  end
end
